// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID      int       `json:"id"`
	Name    *string   `json:"name"`
	Markets []*Market `json:"markets"`
}

type Market struct {
	ID   int     `json:"id"`
	Name *string `json:"name"`
	Odds []*Odd  `json:"odds"`
}

type Odd struct {
	ID    int      `json:"id"`
	Name  *string  `json:"name"`
	Value *float64 `json:"value"`
}

type Offer struct {
	Events []*Event `json:"events"`
}
